### PR TITLE
Add simple-phpunit as dev dependency (and updated tests)

### PR DESCRIPTION
**Pull request by thePanz**
- [x] Added simple-phpunit as -dev dependency
- [x] updated tests with usage of `::class` to get the FQDN of classes.
- [x] Updated minor PHP Version to 5.5
- [x] Updated changelog

### CODE REVIEW

**Comment by Seldaek** [comment]
This has to be rebased it seems

**Comment by thePanz** [comment]
Rebased on latest changes from `master`

**Comment by Seldaek** [comment]
Thanks

**Comment by Seldaek** [comment]
Sent you an invite to be a collaborator, so you can manage releases and all yourself if you are interested in taking over. I don't have a whole lot of time to keep track of things here tbh.

**Comment by Seldaek** [comment]
Feel free to email me or ask in an issue though if anything is unclear or you have doubts regarding some changes.

**Comment by Seldaek** [comment]
And last comment, the build is failing :) https://travis-ci.org/nelmio/NelmioSolariumBundle

**Comment by thePanz** [comment]
Thanks @Seldaek :)
I will have a look at the failing tests on Travis (I just noticed it was related to PHP 7.1)

**Pull request merged**
