### PR TITLE
fix deprecations introduced in Solarium 5.2

### PR DESCRIPTION
**Pull request by dmaicher**
Fixes https://github.com/nelmio/NelmioSolariumBundle/issues/101

This makes the bundle fully compatible with the changes introduced in Solarium 5.2 and therefore (as of now) with the upcoming Solarium 6 :sunglasses: 

See https://github.com/solariumphp/solarium/releases/tag/5.2.0

I also dropped Symfony 3.4 support as Solarium 5.2 requires at least `symfony/event-dispatcher` `^4.3`.

This should be released as `4.1.0` then I think.

Deprecations on master with Solarium 5.2 before this PR:

```
Remaining indirect deprecation notices (30)

  14x: Not passing an instance of AdapterInterface as the first constructor argument is deprecated in Solarium 5.2 and will cause an error in Solarium 6.
    2x in NelmioSolariumExtensionTest::testDefaultClient from Nelmio\SolariumBundle\Tests
    2x in NelmioSolariumExtensionTest::testClientRegistry from Nelmio\SolariumBundle\Tests
    1x in NelmioSolariumExtensionTest::testLoadEmptyConfiguration from Nelmio\SolariumBundle\Tests
    1x in NelmioSolariumExtensionTest::testNoClients from Nelmio\SolariumBundle\Tests
    1x in NelmioSolariumExtensionTest::testLoadCustomAdapter from Nelmio\SolariumBundle\Tests
    1x in NelmioSolariumExtensionTest::testLoadCustomClient from Nelmio\SolariumBundle\Tests
    1x in NelmioSolariumExtensionTest::testPlugins from Nelmio\SolariumBundle\Tests
    1x in NelmioSolariumExtensionTest::testEndpoints from Nelmio\SolariumBundle\Tests
    1x in NelmioSolariumExtensionTest::testSpecificEndpoints from Nelmio\SolariumBundle\Tests
    1x in NelmioSolariumExtensionTest::testDefaultEndpoint from Nelmio\SolariumBundle\Tests
    1x in NelmioSolariumExtensionTest::testLogger from Nelmio\SolariumBundle\Tests
    1x in NelmioSolariumExtensionTest::testLoadBalancer from Nelmio\SolariumBundle\Tests

  14x: Not passing an instance of EventDispatcherInterface as the second constructor argument is deprecated in Solarium 5.2 and will cause an error in Solarium 6.
    2x in NelmioSolariumExtensionTest::testDefaultClient from Nelmio\SolariumBundle\Tests
    2x in NelmioSolariumExtensionTest::testClientRegistry from Nelmio\SolariumBundle\Tests
    1x in NelmioSolariumExtensionTest::testLoadEmptyConfiguration from Nelmio\SolariumBundle\Tests
    1x in NelmioSolariumExtensionTest::testNoClients from Nelmio\SolariumBundle\Tests
    1x in NelmioSolariumExtensionTest::testLoadCustomAdapter from Nelmio\SolariumBundle\Tests
    1x in NelmioSolariumExtensionTest::testLoadCustomClient from Nelmio\SolariumBundle\Tests
    1x in NelmioSolariumExtensionTest::testPlugins from Nelmio\SolariumBundle\Tests
    1x in NelmioSolariumExtensionTest::testEndpoints from Nelmio\SolariumBundle\Tests
    1x in NelmioSolariumExtensionTest::testSpecificEndpoints from Nelmio\SolariumBundle\Tests
    1x in NelmioSolariumExtensionTest::testDefaultEndpoint from Nelmio\SolariumBundle\Tests
    1x in NelmioSolariumExtensionTest::testLogger from Nelmio\SolariumBundle\Tests
    1x in NelmioSolariumExtensionTest::testLoadBalancer from Nelmio\SolariumBundle\Tests

  1x: The Client option "adapter" is deprecated since Solarium 5.2 and will be removed in Solarium 6. Pass an instance of AdapterInterface to the constructor instead.
    1x in NelmioSolariumExtensionTest::testLoadCustomAdapter from Nelmio\SolariumBundle\Tests

  1x: Passing a string to Client::setAdapter is deprecated since Solarium 5.2 and will cause an error in Solarium 6. Pass an instance of AdapterInterface instead.
    1x in NelmioSolariumExtensionTest::testLoadCustomAdapter from Nelmio\SolariumBundle\Tests

Other deprecation notices (2)

  2x: Endpoint::getTimeout is deprecated since Solarium 5.2 and will be removed in Solarium 6. Configure the timeout on the HTTP Client used by the Adapter instead.
    1x in NelmioSolariumExtensionTest::testLoadEmptyConfiguration from Nelmio\SolariumBundle\Tests
    1x in NelmioSolariumExtensionTest::testNoClients from Nelmio\SolariumBundle\Tests
```

### CODE REVIEW

**Comment by dmaicher** [comment]
@thePanz ready for review now

**Comment by dmaicher** [comment]
@Seldaek @thePanz any chance you guys could have a look at this one?

**Comment by dmaicher** [comment]
Due to the lack of feedback I decided to maintain my own [bundle](https://github.com/dmaicher/solarium-bundle) instead. 

Also the latest release is still the RC from December last year: https://github.com/nelmio/NelmioSolariumBundle/releases/tag/v4.0.0-rc.1

This bundle seems abandoned.

**Comment by thePanz** [comment]
@dmaicher I pulled in your changes into the `master` branch.
I started a new 5.x alias, as those changes are not for a "minor" change

Thank you for the PR!

**Comment by tjveldhuizen** [comment]
Thanks for the effort fixing the deprecations. My test suite is flooded with deprecation warnings, so I'ld love to upgrade to a new release of this bundle. Is there something I can (try to) do/test to help releasing the 4.1.0? Or is it just a case of 'finding time to do so', for you?

**Pull request closed without merging**
