### PR TITLE
Add support for adapteroptions.

### PR DESCRIPTION
**Pull request by keesschepers**
The solarium client also accepts "adapteroptions" for in our case to support having a proxy set.

Configuration will be:

```
nelmio_solarium:
    endpoints:
        .....
    clients:
        default:
            .....
            adapteroptions:
                proxy: ~
```

### CODE REVIEW

**Comment by Seldaek** [comment]
Would you mind making that adapter_options? Or just options? Not sure what makes more sense but it should be more readable at least :)

**Comment by keesschepers** [comment]
Hello @Seldaek I updated the pull-request. Also with this change we are dependend on the master branch because previous versions of Solarium don't support a proxy option. Do you want me to rebase and squash my commits?

**Comment by Seldaek** [comment]
Depending on master makes it a no-go right now for me. A way to fix this I assume would be to make solarium add a [branch-alias](https://getcomposer.org/doc/articles/aliases.md#branch-alias) so you can require `3.*@dev` in your project to get dev-master, but we can still require `~3.2` as I guess the adapter options were already available in 3.2?

**Comment by dmaicher** [comment]
This should be closed since the `adapteroptions` are deprecated in the upcoming Solarium 5.2 and removed in 6.0.

**Pull request closed without merging**
