### PR TITLE
Fix result serialization by removing Reference on Symfony EventDispat…

### PR DESCRIPTION
**Pull request by MortalFlesh**
Hello,
I have same problem as this issue: https://github.com/nelmio/NelmioSolariumBundle/issues/62

And I found that this commit seems to cause the problem: https://github.com/nelmio/NelmioSolariumBundle/commit/fede21be1af5b81aeffd9c759dc4dec4f137bed3

So I decided to send a PR to remove this line.

### CODE REVIEW

**Comment by Seldaek** [comment]
Doing this breaks the use case in https://github.com/nelmio/NelmioSolariumBundle/pull/58 so I'm not sure what to do here.

**Comment by MortalFlesh** [comment]
Well I didnt dig into `EventDispatcher` usage in your bundle, but it seems to me that it worked fine before. So is it really that important to use the one from Symfony?

**Comment by Seldaek** [comment]
It's not used in the bundle, but it lets people use it in their applications.

**Comment by MortalFlesh** [comment]
Oh I see.. so Im not sure if we could came up with solution here.. We might get rid of those dependencies before serializing an Result .. or maybe implement `Serializable` in Result class in Solarium .. 

Or is there any idea you would suggest?

**Comment by Seldaek** [comment]
I think customizing the serialization or ideally fixing that in Solarium itself sounds like the better option.

**Pull request closed without merging**
