### PR TITLE
new solarium client signature

### PR DESCRIPTION
**Pull request by wickedOne**
changed the nelmio solarium extension so it plays nice with the new solarium 5.x client signature

### CODE REVIEW

**Comment by dmaicher** [comment]
Just FYI: I also tried contributing this. See https://github.com/nelmio/NelmioSolariumBundle/pull/100

**Comment by wickedOne** [comment]
ugh, ok thanx for the heads up

**Comment by thePanz** [comment]
@wickedOne : the changes from #100 have been merged into the `master` branch

**Comment by dmaicher** [comment]
@wickedOne can you check my changes that have been merged?`I think they cover all deprecations introduced in Solarium 5.2

**Comment by wickedOne** [comment]
@dmaicher yes, looks like you've covered everything, thanks!
@thePanz thanks for merging!

**Pull request closed without merging**
